<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/masterpages/Detail.Master" 
         Inherits="CorporateCitizenship.Web.OurActions.TechnologyInnovation.EconomicImpact.DefaultPage" Src="default.aspx.cs" %>

<asp:Content ID="Content5" ContentPlaceHolderID="head" runat="server">
    <title>Economic Impact</title>
    <meta name="keywords" content="Microsoft Corporate Citizenship" />
    <meta name="description" content="" />
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="header_title" runat="server">
    <h1>Economic Impact</h1>
</asp:Content>

<%-- breadcrumbs --%>
<asp:Content ID="Content1" ContentPlaceHolderID="breadcrumbs" runat="server">
    <li><a id="A1" runat="server" href="~/">Home</a> &gt;</li>
    <li><a id="A2" runat="server" href="~/our-actions">Our Actions</a> &gt;</li>
    <li><a id="A3" runat="server" href="~/our-actions/technology-innovation">Technology Innovation</a> &gt;</li>
    <li class="last">Economic Impact</li>
</asp:Content>

<%-- primary content block --%>
<asp:Content ID="Content2" ContentPlaceHolderID="primary_block" runat="server">

    <p class="intro">The IT industry contributes to global economic growth and, together with the innovation it fosters, is an essential driver of competitive 21st century economies.</p>

    <p class="intro">Microsoft has a direct economic impact in the places we do business. In 2009 we directly employed 93,000 full-time staff, 56,000 in the United States and 37,000 internationally.</p>

    <p>Beyond our direct impact, our business model relies on a network of partners that are tremendously valuable to their own communities; and generate further innovation, growth and opportunity. A 2009 study by research firm International Data Corp (IDC) found the software industry is an especially important part of the IT sector, helping stimulate economic recovery, growth and job creation. Findings included:</p>

    <ul class="formatted-list">

        <li>Microsoft has nearly 700,000 local partners&#151;most of which are small and medium-sized enterprises&#151;which develop, market, retail, and service our products.</li>
        <li>Our local partners and the Microsoft ecosystem employ 14.9 million people, make approximately $537 billion of their own revenue, and invest $175 billion in their local economies.</li>
        <li>Revenues generated by Microsoft partners remain in local communities: for every dollar of revenue made by Microsoft, local partners make $8.70 for themselves and their local economies.</li>

    </ul>

    <p>Microsoft also runs programs to support start-up software companies. For example, we offer free products, guidance and visibility to potential investors and clients through Microsoft BizSpark. We helped 23,000 start-ups in the first eleven months of the program, which are supported by a network of 1,800 venture capital partners, government agencies and incubators.</p>

<div class="clearer"></div>    
<br />
<div id="top-story" class="panel">     

    <h2 class="miniheader yellow">IDC Economic Impact Study</h2>

    <p>Learn more about how the global technology industry, the software sector, and Microsoft’s business model create jobs and drive local economic growth:</p>

    <ul class="links">
		<li><a href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/2009_OCT_Global_White_Paper_IDC_2009_Study.pdf" class="arrow down">IDC White Paper</a></li>
		<li><a href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/AP_IDC_2009_Study.pdf " class="arrow down">Asia Pacific study</a></li>
		<li><a href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/CEE_IDC_2009_Study.pdf" class="arrow down">Central and Eastern Europe study</a></li>
		<li><a href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/EU_IDC_2009_Study.pdf" class="arrow down">European Union study</a></li>
		<li><a href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/LA_IDC_2009_Study.pdf" class="arrow down">Latin America study</a></li>
		<li><a href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/MEA_IDC_2009_Study.pdf" class="arrow down">Middle East and Africa study</a></li>
		<li><a href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/NA_IDC_2009_Study.pdf" class="arrow down">North America study</a></li>
    </ul>
    
    <p>The IDC studies are available for the following countries (PDF file, up to 250 KB)</p>
    
    <table cellspacing="0" cellpadding="0" class="worldwide">
            <tbody><tr class="headerRow">
              <td>North America</td>
              <td>Western Europe (EU)</td>
              <td>Central and Eastern Europe</td>
              <td>Middle East and Africa</td>
              <td>Latin America</td>
              <td>Asia Pacific</td>
            </tr>
            <tr class="dataRow">
              <td>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/US_IDC_2009_Study.pdf">United States</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Canada_IDC_2009_Study.pdf">Canada</a>
              </td>
              <td>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Austria_IDC_2009_Study.pdf">Austria</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Belguim_IDC_2009_Study.pdf">Belgium</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Denmark_IDC_2009_Study.pdf">Denmark</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Finland_IDC_2009_Study.pdf">Finland</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/France_IDC_2009_Study.pdf">France</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Germany_IDC_2009_Study.pdf">Germany</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Ireland_IDC_2009_Study.pdf">Ireland</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Italy_IDC_2009_Study.pdf">Italy</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Netherlands_IDC_2009_Study.pdf">Netherlands</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Norway_IDC_2009_Study.pdf">Norway</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Portugal_IDC_2009_Study.pdf">Portugal</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Spain_IDC_2009_Study.pdf">Spain</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Sweden_IDC_2009_Study.pdf">Sweden</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Switzerland_IDC_2009_Study.pdf">Switzerland</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/UK_IDC_2009_Study.pdf">United Kingdom</a>
                <br/>
              </td>
              <td>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Bulgaria_IDC_2009_Study.pdf">Bulgaria</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Croatia_IDC_2009_Study.pdf">Croatia</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Czech_Republic_IDC_2009_Study.pdf">Czech Republic</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Greece_IDC_2009_Study.pdf">Greece</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Hungary_IDC_2009_Study.pdf">Hungary</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Poland_IDC_2009_Study.pdf">Poland</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Romania_IDC_2009_Study.pdf">Romania</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Russia_IDC_2009_Study.pdf">Russia</a>
                <br/>
              </td>
              <td>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Egypt_IDC_2009_Study.pdf">Egypt</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Israel_IDC_2009_Study.pdf">Israel</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Saudi_Arabia_IDC_2009_Study.pdf">Saudi Arabia</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/South_Africa_IDC_2009_Study.pdf">South Africa</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Turkey_IDC_2009_Study.pdf">Turkey</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/UAE_IDC_2009_Study.pdf">UAE</a>
                <br/>
              </td>
              <td>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Argentina_IDC_2009_Study.pdf">Argentina</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Brazil_IDC_2009_Study.pdf">Brazil</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Chile_IDC_2009_Study.pdf">Chile</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Colombia_IDC_2009_Study.pdf">Colombia</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Mexico_IDC_2009_Study.pdf">Mexico</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Peru_IDC_2009_Study.pdf">Peru</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/D/3/3/D3346D96-DBBC-4AC0-B3EF-60BFDA205470/Venezuela_IDC_2009_Study.pdf">Venezuela</a>
                <br/>
              </td>
              <td>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Australia_IDC_2009_Study.pdf">Australia</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/China_IDC_2009_Study.pdf">China</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Hong_Kong_IDC_2009_Study.pdf">Hong Kong</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/India_IDC_2009_Study.pdf">India</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Indonesia_IDC_2009_Study.pdf">Indonesia</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Japan_IDC_2009_Study.pdf">Japan</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Malaysia_IDC_2009_Study.pdf">Malaysia</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/New_Zealand_IDC_2009_Study.pdf">New Zealand</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Philippines_IDC_2009_Study.pdf">Philippines</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Singapore_IDC_2009_Study.pdf">Singapore</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/South_Korea_IDC_2009_Study_9_24_09.pdf">South Korea</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Taiwan_IDC_2009_Study.pdf">Taiwan</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Thailand_IDC_2009_Study.pdf">Thailand</a>
                <br/>
                <a class="arrow down"  target="_blank" title="" href="http://download.microsoft.com/download/5/3/8/5384A1B0-58D6-4F6F-8AD3-0A8224E5B031/Vietnam_IDC_2009_Study.pdf">Vietnam</a>
                <br/>
              </td>
            </tr>
          </tbody>
     </table>
</div>     
     
 <div class="panel">     
     <h2 class="miniheader yellow">Related Links</h2>
     
     <ul class="links">
        <li><a href="http://www.microsoft.com/bizspark" class="arrow diagonal">Microsoft BizSpark</a></li>
     </ul>
     
 </div>

</asp:Content>

<%-- secondary content block --%>
<asp:Content ID="Content3" ContentPlaceHolderID="secondary_block" runat="server">
<div id="local-impact">	
		<img alt="Microsoft Local Impact" runat="server" src="~/images/home/microsoft-local-impact.png" />
		<p>The Local Impact Map shows how Microsoft and its partners enable social and economic opportunity in communities everywhere.</p>
	
		

        <div id="todays-story" class="filler"></div>
</div>
</asp:Content>
